# Generated by Django 5.1.4 on 2024-12-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_file', models.FileField(upload_to='')),
            ],
        ),
    ]
